In [4]:
name = input("Enter your name: ")
age  = input("Enter your age: ")
print("Hello", name,". you are", age, "years old.")

Enter your name:  mean
Enter your age:  90


Hello mean . you are 90 years old.


In [24]:
mark = int(input("Enter your mark: "))
if (mark >= 50): print("Student Pass.")
else: print("Student Fail.")

Enter your mark:  54


Student Pass.


In [17]:
import numpy as np

arr = np.array([12, 5, 8, 20, 3, 15])

min_arr = np.min(arr)
max_arr = np.max(arr)
scaler_arr = (5 * arr)

print(min_arr)
print(max_arr)
print(scaler_arr)

3
20
[ 60  25  40 100  15  75]


In [19]:
import numpy as np

rand_num = np.random.randint(0, 10, size=5)

print(rand_num)

[8 6 7 1 3]


In [22]:


import numpy as np

a = np.array([[1, 2],
              [3, 4]])

tran_a = a.T

print(tran_a)

[[1 3]
 [2 4]]
